#pragma once

#include <array>
#include <vector>

using std::array;
using std::vector;

class Records;

class TALib {
public:
    vector<double> ATR(vector<double> &high, vector<double> &low, vector<double> &close, int optInTimePeriod = 14);
    vector<double> ATR(Records &r, int optInTimePeriod = 14);
    vector<double> NATR(vector<double> &high, vector<double> &low, vector<double> &close, int optInTimePeriod = 14);
    vector<double> NATR(Records &r, int optInTimePeriod = 14);
    vector<double> TRANGE(vector<double> &high, vector<double> &low, vector<double> &close);
    vector<double> TRANGE(Records &r);
    vector<double> DEMA(vector<double> &close, int optInTimePeriod = 30);
    vector<double> DEMA(Records &r, int optInTimePeriod = 30);
    vector<double> EMA(vector<double> &close, int optInTimePeriod = 30);
    vector<double> EMA(Records &r, int optInTimePeriod = 30);
    vector<double> HT_TRENDLINE(vector<double> &close);
    vector<double> HT_TRENDLINE(Records &r);
    vector<double> KAMA(vector<double> &close, int optInTimePeriod = 30);
    vector<double> KAMA(Records &r, int optInTimePeriod = 30);
    vector<double> MA(vector<double> &close, int optInTimePeriod = 30, int optInMAType = 0);
    vector<double> MA(Records &r, int optInTimePeriod = 30, int optInMAType = 0);
    vector<double> MIDPOINT(vector<double> &close, int optInTimePeriod = 14);
    vector<double> MIDPOINT(Records &r, int optInTimePeriod = 14);
    vector<double> MIDPRICE(vector<double> &high, vector<double> &low, int optInTimePeriod = 14);
    vector<double> MIDPRICE(Records &r, int optInTimePeriod = 14);
    vector<double> SAR(vector<double> &high, vector<double> &low, double optInAcceleration = 0.02, double optInMaximum = 0.2);
    vector<double> SAR(Records &r, double optInAcceleration = 0.02, double optInMaximum = 0.2);
    vector<double> SAREXT(vector<double> &high, vector<double> &low, double optInStartValue = 0, double optInOffsetOnReverse = 0, double optInAccelerationInitLong = 0.02, double optInAccelerationLong = 0.02, double optInAccelerationMaxLong = 0.2, double optInAccelerationInitShort = 0.02, double optInAccelerationShort = 0.02, double optInAccelerationMaxShort = 0.2);
    vector<double> SAREXT(Records &r, double optInStartValue = 0, double optInOffsetOnReverse = 0, double optInAccelerationInitLong = 0.02, double optInAccelerationLong = 0.02, double optInAccelerationMaxLong = 0.2, double optInAccelerationInitShort = 0.02, double optInAccelerationShort = 0.02, double optInAccelerationMaxShort = 0.2);
    vector<double> SMA(vector<double> &close, int optInTimePeriod = 30);
    vector<double> SMA(Records &r, int optInTimePeriod = 30);
    vector<double> T3(vector<double> &close, int optInTimePeriod = 5, double optInVFactor = 0.7);
    vector<double> T3(Records &r, int optInTimePeriod = 5, double optInVFactor = 0.7);
    vector<double> TEMA(vector<double> &close, int optInTimePeriod = 30);
    vector<double> TEMA(Records &r, int optInTimePeriod = 30);
    vector<double> TRIMA(vector<double> &close, int optInTimePeriod = 30);
    vector<double> TRIMA(Records &r, int optInTimePeriod = 30);
    vector<double> WMA(vector<double> &close, int optInTimePeriod = 30);
    vector<double> WMA(Records &r, int optInTimePeriod = 30);
    vector<double> LINEARREG(vector<double> &close, int optInTimePeriod = 14);
    vector<double> LINEARREG(Records &r, int optInTimePeriod = 14);
    vector<double> LINEARREG_ANGLE(vector<double> &close, int optInTimePeriod = 14);
    vector<double> LINEARREG_ANGLE(Records &r, int optInTimePeriod = 14);
    vector<double> LINEARREG_INTERCEPT(vector<double> &close, int optInTimePeriod = 14);
    vector<double> LINEARREG_INTERCEPT(Records &r, int optInTimePeriod = 14);
    vector<double> LINEARREG_SLOPE(vector<double> &close, int optInTimePeriod = 14);
    vector<double> LINEARREG_SLOPE(Records &r, int optInTimePeriod = 14);
    vector<double> STDDEV(vector<double> &close, int optInTimePeriod = 5, double optInNbDev = 1);
    vector<double> STDDEV(Records &r, int optInTimePeriod = 5, double optInNbDev = 1);
    vector<double> TSF(vector<double> &close, int optInTimePeriod = 14);
    vector<double> TSF(Records &r, int optInTimePeriod = 14);
    vector<double> VAR(vector<double> &close, int optInTimePeriod = 5, double optInNbDev = 1);
    vector<double> VAR(Records &r, int optInTimePeriod = 5, double optInNbDev = 1);
    vector<double> ADX(vector<double> &high, vector<double> &low, vector<double> &close, int optInTimePeriod = 14);
    vector<double> ADX(Records &r, int optInTimePeriod = 14);
    vector<double> ADXR(vector<double> &high, vector<double> &low, vector<double> &close, int optInTimePeriod = 14);
    vector<double> ADXR(Records &r, int optInTimePeriod = 14);
    vector<double> APO(vector<double> &close, int optInFastPeriod = 12, int optInSlowPeriod = 26, int optInMAType = 0);
    vector<double> APO(Records &r, int optInFastPeriod = 12, int optInSlowPeriod = 26, int optInMAType = 0);
    vector<double> AROONOSC(vector<double> &high, vector<double> &low, int optInTimePeriod = 14);
    vector<double> AROONOSC(Records &r, int optInTimePeriod = 14);
    vector<double> BOP(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<double> BOP(Records &r);
    vector<double> CCI(vector<double> &high, vector<double> &low, vector<double> &close, int optInTimePeriod = 14);
    vector<double> CCI(Records &r, int optInTimePeriod = 14);
    vector<double> CMO(vector<double> &close, int optInTimePeriod = 14);
    vector<double> CMO(Records &r, int optInTimePeriod = 14);
    vector<double> DX(vector<double> &high, vector<double> &low, vector<double> &close, int optInTimePeriod = 14);
    vector<double> DX(Records &r, int optInTimePeriod = 14);
    vector<double> MFI(vector<double> &high, vector<double> &low, vector<double> &close, vector<double> &volume, int optInTimePeriod = 14);
    vector<double> MFI(Records &r, int optInTimePeriod = 14);
    vector<double> MINUS_DI(vector<double> &high, vector<double> &low, vector<double> &close, int optInTimePeriod = 14);
    vector<double> MINUS_DI(Records &r, int optInTimePeriod = 14);
    vector<double> MINUS_DM(vector<double> &high, vector<double> &low, int optInTimePeriod = 14);
    vector<double> MINUS_DM(Records &r, int optInTimePeriod = 14);
    vector<double> MOM(vector<double> &close, int optInTimePeriod = 10);
    vector<double> MOM(Records &r, int optInTimePeriod = 10);
    vector<double> PLUS_DI(vector<double> &high, vector<double> &low, vector<double> &close, int optInTimePeriod = 14);
    vector<double> PLUS_DI(Records &r, int optInTimePeriod = 14);
    vector<double> PLUS_DM(vector<double> &high, vector<double> &low, int optInTimePeriod = 14);
    vector<double> PLUS_DM(Records &r, int optInTimePeriod = 14);
    vector<double> PPO(vector<double> &close, int optInFastPeriod = 12, int optInSlowPeriod = 26, int optInMAType = 0);
    vector<double> PPO(Records &r, int optInFastPeriod = 12, int optInSlowPeriod = 26, int optInMAType = 0);
    vector<double> ROC(vector<double> &close, int optInTimePeriod = 10);
    vector<double> ROC(Records &r, int optInTimePeriod = 10);
    vector<double> ROCP(vector<double> &close, int optInTimePeriod = 10);
    vector<double> ROCP(Records &r, int optInTimePeriod = 10);
    vector<double> ROCR(vector<double> &close, int optInTimePeriod = 10);
    vector<double> ROCR(Records &r, int optInTimePeriod = 10);
    vector<double> ROCR100(vector<double> &close, int optInTimePeriod = 10);
    vector<double> ROCR100(Records &r, int optInTimePeriod = 10);
    vector<double> RSI(vector<double> &close, int optInTimePeriod = 14);
    vector<double> RSI(Records &r, int optInTimePeriod = 14);
    vector<double> TRIX(vector<double> &close, int optInTimePeriod = 30);
    vector<double> TRIX(Records &r, int optInTimePeriod = 30);
    vector<double> ULTOSC(vector<double> &high, vector<double> &low, vector<double> &close, int optInTimePeriod1 = 7, int optInTimePeriod2 = 14, int optInTimePeriod3 = 28);
    vector<double> ULTOSC(Records &r, int optInTimePeriod1 = 7, int optInTimePeriod2 = 14, int optInTimePeriod3 = 28);
    vector<double> WILLR(vector<double> &high, vector<double> &low, vector<double> &close, int optInTimePeriod = 14);
    vector<double> WILLR(Records &r, int optInTimePeriod = 14);
    vector<int> CDL2CROWS(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDL2CROWS(Records &r);
    vector<int> CDL3BLACKCROWS(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDL3BLACKCROWS(Records &r);
    vector<int> CDL3INSIDE(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDL3INSIDE(Records &r);
    vector<int> CDL3LINESTRIKE(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDL3LINESTRIKE(Records &r);
    vector<int> CDL3OUTSIDE(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDL3OUTSIDE(Records &r);
    vector<int> CDL3STARSINSOUTH(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDL3STARSINSOUTH(Records &r);
    vector<int> CDL3WHITESOLDIERS(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDL3WHITESOLDIERS(Records &r);
    vector<int> CDLABANDONEDBABY(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close, double optInPenetration = 0.3);
    vector<int> CDLABANDONEDBABY(Records &r, double optInPenetration = 0.3);
    vector<int> CDLADVANCEBLOCK(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLADVANCEBLOCK(Records &r);
    vector<int> CDLBELTHOLD(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLBELTHOLD(Records &r);
    vector<int> CDLBREAKAWAY(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLBREAKAWAY(Records &r);
    vector<int> CDLCLOSINGMARUBOZU(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLCLOSINGMARUBOZU(Records &r);
    vector<int> CDLCONCEALBABYSWALL(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLCONCEALBABYSWALL(Records &r);
    vector<int> CDLCOUNTERATTACK(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLCOUNTERATTACK(Records &r);
    vector<int> CDLDARKCLOUDCOVER(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close, double optInPenetration = 0.5);
    vector<int> CDLDARKCLOUDCOVER(Records &r, double optInPenetration = 0.5);
    vector<int> CDLDOJI(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLDOJI(Records &r);
    vector<int> CDLDOJISTAR(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLDOJISTAR(Records &r);
    vector<int> CDLDRAGONFLYDOJI(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLDRAGONFLYDOJI(Records &r);
    vector<int> CDLENGULFING(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLENGULFING(Records &r);
    vector<int> CDLEVENINGDOJISTAR(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close, double optInPenetration = 0.3);
    vector<int> CDLEVENINGDOJISTAR(Records &r, double optInPenetration = 0.3);
    vector<int> CDLEVENINGSTAR(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close, double optInPenetration = 0.3);
    vector<int> CDLEVENINGSTAR(Records &r, double optInPenetration = 0.3);
    vector<int> CDLGAPSIDESIDEWHITE(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLGAPSIDESIDEWHITE(Records &r);
    vector<int> CDLGRAVESTONEDOJI(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLGRAVESTONEDOJI(Records &r);
    vector<int> CDLHAMMER(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLHAMMER(Records &r);
    vector<int> CDLHANGINGMAN(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLHANGINGMAN(Records &r);
    vector<int> CDLHARAMI(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLHARAMI(Records &r);
    vector<int> CDLHARAMICROSS(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLHARAMICROSS(Records &r);
    vector<int> CDLHIGHWAVE(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLHIGHWAVE(Records &r);
    vector<int> CDLHIKKAKE(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLHIKKAKE(Records &r);
    vector<int> CDLHIKKAKEMOD(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLHIKKAKEMOD(Records &r);
    vector<int> CDLHOMINGPIGEON(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLHOMINGPIGEON(Records &r);
    vector<int> CDLIDENTICAL3CROWS(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLIDENTICAL3CROWS(Records &r);
    vector<int> CDLINNECK(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLINNECK(Records &r);
    vector<int> CDLINVERTEDHAMMER(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLINVERTEDHAMMER(Records &r);
    vector<int> CDLKICKING(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLKICKING(Records &r);
    vector<int> CDLKICKINGBYLENGTH(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLKICKINGBYLENGTH(Records &r);
    vector<int> CDLLADDERBOTTOM(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLLADDERBOTTOM(Records &r);
    vector<int> CDLLONGLEGGEDDOJI(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLLONGLEGGEDDOJI(Records &r);
    vector<int> CDLLONGLINE(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLLONGLINE(Records &r);
    vector<int> CDLMARUBOZU(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLMARUBOZU(Records &r);
    vector<int> CDLMATCHINGLOW(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLMATCHINGLOW(Records &r);
    vector<int> CDLMATHOLD(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close, double optInPenetration = 0.5);
    vector<int> CDLMATHOLD(Records &r, double optInPenetration = 0.5);
    vector<int> CDLMORNINGDOJISTAR(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close, double optInPenetration = 0.3);
    vector<int> CDLMORNINGDOJISTAR(Records &r, double optInPenetration = 0.3);
    vector<int> CDLMORNINGSTAR(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close, double optInPenetration = 0.3);
    vector<int> CDLMORNINGSTAR(Records &r, double optInPenetration = 0.3);
    vector<int> CDLONNECK(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLONNECK(Records &r);
    vector<int> CDLPIERCING(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLPIERCING(Records &r);
    vector<int> CDLRICKSHAWMAN(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLRICKSHAWMAN(Records &r);
    vector<int> CDLRISEFALL3METHODS(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLRISEFALL3METHODS(Records &r);
    vector<int> CDLSEPARATINGLINES(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLSEPARATINGLINES(Records &r);
    vector<int> CDLSHOOTINGSTAR(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLSHOOTINGSTAR(Records &r);
    vector<int> CDLSHORTLINE(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLSHORTLINE(Records &r);
    vector<int> CDLSPINNINGTOP(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLSPINNINGTOP(Records &r);
    vector<int> CDLSTALLEDPATTERN(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLSTALLEDPATTERN(Records &r);
    vector<int> CDLSTICKSANDWICH(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLSTICKSANDWICH(Records &r);
    vector<int> CDLTAKURI(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLTAKURI(Records &r);
    vector<int> CDLTASUKIGAP(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLTASUKIGAP(Records &r);
    vector<int> CDLTHRUSTING(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLTHRUSTING(Records &r);
    vector<int> CDLTRISTAR(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLTRISTAR(Records &r);
    vector<int> CDLUNIQUE3RIVER(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLUNIQUE3RIVER(Records &r);
    vector<int> CDLUPSIDEGAP2CROWS(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLUPSIDEGAP2CROWS(Records &r);
    vector<int> CDLXSIDEGAP3METHODS(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<int> CDLXSIDEGAP3METHODS(Records &r);
    vector<double> AD(vector<double> &high, vector<double> &low, vector<double> &close, vector<double> &volume);
    vector<double> AD(Records &r);
    vector<double> ADOSC(vector<double> &high, vector<double> &low, vector<double> &close, vector<double> &volume, int optInFastPeriod = 3, int optInSlowPeriod = 10);
    vector<double> ADOSC(Records &r, int optInFastPeriod = 3, int optInSlowPeriod = 10);
    vector<double> OBV(vector<double> &close, vector<double> &volume);
    vector<double> OBV(Records &r);
    vector<double> MAX(vector<double> &close, int optInTimePeriod = 30);
    vector<double> MAX(Records &r, int optInTimePeriod = 30);
    vector<int> MAXINDEX(vector<double> &close, int optInTimePeriod = 30);
    vector<int> MAXINDEX(Records &r, int optInTimePeriod = 30);
    vector<double> MIN(vector<double> &close, int optInTimePeriod = 30);
    vector<double> MIN(Records &r, int optInTimePeriod = 30);
    vector<int> MININDEX(vector<double> &close, int optInTimePeriod = 30);
    vector<int> MININDEX(Records &r, int optInTimePeriod = 30);
    vector<double> SUM(vector<double> &close, int optInTimePeriod = 30);
    vector<double> SUM(Records &r, int optInTimePeriod = 30);
    vector<double> ACOS(vector<double> &close);
    vector<double> ACOS(Records &r);
    vector<double> ASIN(vector<double> &close);
    vector<double> ASIN(Records &r);
    vector<double> ATAN(vector<double> &close);
    vector<double> ATAN(Records &r);
    vector<double> CEIL(vector<double> &close);
    vector<double> CEIL(Records &r);
    vector<double> COS(vector<double> &close);
    vector<double> COS(Records &r);
    vector<double> COSH(vector<double> &close);
    vector<double> COSH(Records &r);
    vector<double> EXP(vector<double> &close);
    vector<double> EXP(Records &r);
    vector<double> FLOOR(vector<double> &close);
    vector<double> FLOOR(Records &r);
    vector<double> LN(vector<double> &close);
    vector<double> LN(Records &r);
    vector<double> LOG10(vector<double> &close);
    vector<double> LOG10(Records &r);
    vector<double> SIN(vector<double> &close);
    vector<double> SIN(Records &r);
    vector<double> SINH(vector<double> &close);
    vector<double> SINH(Records &r);
    vector<double> SQRT(vector<double> &close);
    vector<double> SQRT(Records &r);
    vector<double> TAN(vector<double> &close);
    vector<double> TAN(Records &r);
    vector<double> TANH(vector<double> &close);
    vector<double> TANH(Records &r);
    vector<double> AVGPRICE(vector<double> &open, vector<double> &high, vector<double> &low, vector<double> &close);
    vector<double> AVGPRICE(Records &r);
    vector<double> MEDPRICE(vector<double> &high, vector<double> &low);
    vector<double> MEDPRICE(Records &r);
    vector<double> TYPPRICE(vector<double> &high, vector<double> &low, vector<double> &close);
    vector<double> TYPPRICE(Records &r);
    vector<double> WCLPRICE(vector<double> &high, vector<double> &low, vector<double> &close);
    vector<double> WCLPRICE(Records &r);
    vector<double> HT_DCPERIOD(vector<double> &close);
    vector<double> HT_DCPERIOD(Records &r);
    vector<double> HT_DCPHASE(vector<double> &close);
    vector<double> HT_DCPHASE(Records &r);
    vector<int> HT_TRENDMODE(vector<double> &close);
    vector<int> HT_TRENDMODE(Records &r);

    // ---- 多输出指标（返回 array<vector<...>, N>，签名与 backtest/cpp/talib.hpp 一致） ----
    array<vector<double>, 2> AROON(vector<double> &high, vector<double> &low, int optInTimePeriod = 14);
    array<vector<double>, 2> AROON(Records &r, int optInTimePeriod = 14);
    array<vector<double>, 3> BBANDS(vector<double> &close, int optInTimePeriod = 5, double optInNbDevUp = 2, double optInNbDevDn = 2, int optInMAType = 0);
    array<vector<double>, 3> BBANDS(Records &r, int optInTimePeriod = 5, double optInNbDevUp = 2, double optInNbDevDn = 2, int optInMAType = 0);
    array<vector<double>, 2> HT_PHASOR(vector<double> &close);
    array<vector<double>, 2> HT_PHASOR(Records &r);
    array<vector<double>, 2> HT_SINE(vector<double> &close);
    array<vector<double>, 2> HT_SINE(Records &r);
    array<vector<double>, 3> MACD(vector<double> &close, int optInFastPeriod = 12, int optInSlowPeriod = 26, int optInSignalPeriod = 9);
    array<vector<double>, 3> MACD(Records &r, int optInFastPeriod = 12, int optInSlowPeriod = 26, int optInSignalPeriod = 9);
    array<vector<double>, 3> MACDEXT(vector<double> &close, int optInFastPeriod = 12, int optInFastMAType = 0, int optInSlowPeriod = 26, int optInSlowMAType = 0, int optInSignalPeriod = 9, int optInSignalMAType = 0);
    array<vector<double>, 3> MACDEXT(Records &r, int optInFastPeriod = 12, int optInFastMAType = 0, int optInSlowPeriod = 26, int optInSlowMAType = 0, int optInSignalPeriod = 9, int optInSignalMAType = 0);
    array<vector<double>, 3> MACDFIX(vector<double> &close, int optInSignalPeriod = 9);
    array<vector<double>, 3> MACDFIX(Records &r, int optInSignalPeriod = 9);
    array<vector<double>, 2> MAMA(vector<double> &close, double optInFastLimit = 0.5, double optInSlowLimit = 0.05);
    array<vector<double>, 2> MAMA(Records &r, double optInFastLimit = 0.5, double optInSlowLimit = 0.05);
    array<vector<double>, 2> MINMAX(vector<double> &close, int optInTimePeriod = 30);
    array<vector<double>, 2> MINMAX(Records &r, int optInTimePeriod = 30);
    array<vector<int>, 2> MINMAXINDEX(vector<double> &close, int optInTimePeriod = 30);
    array<vector<int>, 2> MINMAXINDEX(Records &r, int optInTimePeriod = 30);
    array<vector<double>, 2> STOCH(vector<double> &high, vector<double> &low, vector<double> &close, int optInFastK_Period = 5, int optInSlowK_Period = 3, int optInSlowK_MAType = 0, int optInSlowD_Period = 3, int optInSlowD_MAType = 0);
    array<vector<double>, 2> STOCH(Records &r, int optInFastK_Period = 5, int optInSlowK_Period = 3, int optInSlowK_MAType = 0, int optInSlowD_Period = 3, int optInSlowD_MAType = 0);
    array<vector<double>, 2> STOCHF(vector<double> &high, vector<double> &low, vector<double> &close, int optInFastK_Period = 5, int optInFastD_Period = 3, int optInFastD_MAType = 0);
    array<vector<double>, 2> STOCHF(Records &r, int optInFastK_Period = 5, int optInFastD_Period = 3, int optInFastD_MAType = 0);
    array<vector<double>, 2> STOCHRSI(vector<double> &close, int optInTimePeriod = 14, int optInFastK_Period = 5, int optInFastD_Period = 3, int optInFastD_MAType = 0);
    array<vector<double>, 2> STOCHRSI(Records &r, int optInTimePeriod = 14, int optInFastK_Period = 5, int optInFastD_Period = 3, int optInFastD_MAType = 0);
};

TALib talib;