from typing import Tuple

def WMA(inReal: list[float], optInTimePeriod: int = 30) -> list[float]: ...
def WILLR(high: list[float], low: list[float], close: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def WCLPRICE(high: list[float], low: list[float], close: list[float]) -> list[float]: ...
def VAR(inReal: list[float], optInTimePeriod: int = 5, optInNbDev: float = 1) -> list[float]: ...
def ULTOSC(high: list[float], low: list[float], close: list[float], optInTimePeriod1: int = 7, optInTimePeriod2: int = 14, optInTimePeriod3: int = 28) -> list[float]: ...
def TYPPRICE(high: list[float], low: list[float], close: list[float]) -> list[float]: ...
def TSF(inReal: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def TRIX(inReal: list[float], optInTimePeriod: int = 30) -> list[float]: ...
def TRIMA(inReal: list[float], optInTimePeriod: int = 30) -> list[float]: ...
def TRANGE(high: list[float], low: list[float], close: list[float]) -> list[float]: ...
def TEMA(inReal: list[float], optInTimePeriod: int = 30) -> list[float]: ...
def TANH(inReal: list[float]) -> list[float]: ...
def TAN(inReal: list[float]) -> list[float]: ...
def T3(inReal: list[float], optInTimePeriod: int = 5, optInVFactor: float = 0.7) -> list[float]: ...
def SUM(inReal: list[float], optInTimePeriod: int = 30) -> list[float]: ...
def STOCHRSI(inReal: list[float], optInTimePeriod: int = 14, optInFastK_Period: int = 5, optInFastD_Period: int = 3, optInFastD_MAType: list[int] = 0) -> Tuple[list[float], list[float]]: ...
def STOCHF(high: list[float], low: list[float], close: list[float], optInFastK_Period: int = 5, optInFastD_Period: int = 3, optInFastD_MAType: list[int] = 0) -> Tuple[list[float], list[float]]: ...
def STOCH(high: list[float], low: list[float], close: list[float], optInFastK_Period: int = 5, optInSlowK_Period: int = 3, optInSlowK_MAType: list[int] = 0, optInSlowD_Period: int = 3, optInSlowD_MAType: list[int] = 0) -> Tuple[list[float], list[float]]: ...
def STDDEV(inReal: list[float], optInTimePeriod: int = 5, optInNbDev: float = 1) -> list[float]: ...
def SQRT(inReal: list[float]) -> list[float]: ...
def SMA(inReal: list[float], optInTimePeriod: int = 30) -> list[float]: ...
def SINH(inReal: list[float]) -> list[float]: ...
def SIN(inReal: list[float]) -> list[float]: ...
def SAREXT(high: list[float], low: list[float], optInStartValue: float = 0, optInOffsetOnReverse: float = 0, optInAccelerationInitLong: float = 0.02, optInAccelerationLong: float = 0.02, optInAccelerationMaxLong: float = 0.2, optInAccelerationInitShort: float = 0.02, optInAccelerationShort: float = 0.02, optInAccelerationMaxShort: float = 0.2) -> list[float]: ...
def SAR(high: list[float], low: list[float], optInAcceleration: float = 0.02, optInMaximum: float = 0.2) -> list[float]: ...
def RSI(inReal: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def ROCR100(inReal: list[float], optInTimePeriod: int = 10) -> list[float]: ...
def ROCR(inReal: list[float], optInTimePeriod: int = 10) -> list[float]: ...
def ROCP(inReal: list[float], optInTimePeriod: int = 10) -> list[float]: ...
def ROC(inReal: list[float], optInTimePeriod: int = 10) -> list[float]: ...
def PPO(inReal: list[float], optInFastPeriod: int = 12, optInSlowPeriod: int = 26, optInMAType: list[int] = 0) -> list[float]: ...
def PLUS_DM(high: list[float], low: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def PLUS_DI(high: list[float], low: list[float], close: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def OBV(inReal: list[float], volume: list[float]) -> list[float]: ...
def NATR(high: list[float], low: list[float], close: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def MOM(inReal: list[float], optInTimePeriod: int = 10) -> list[float]: ...
def MINUS_DM(high: list[float], low: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def MINUS_DI(high: list[float], low: list[float], close: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def MINMAXINDEX(inReal: list[float], optInTimePeriod: int = 30) -> Tuple[list[int], list[int]]: ...
def MINMAX(inReal: list[float], optInTimePeriod: int = 30) -> Tuple[list[float], list[float]]: ...
def MININDEX(inReal: list[float], optInTimePeriod: int = 30) -> list[int]: ...
def MIN(inReal: list[float], optInTimePeriod: int = 30) -> list[float]: ...
def MIDPRICE(high: list[float], low: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def MIDPOINT(inReal: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def MFI(high: list[float], low: list[float], close: list[float], volume: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def MEDPRICE(high: list[float], low: list[float]) -> list[float]: ...
def MAXINDEX(inReal: list[float], optInTimePeriod: int = 30) -> list[int]: ...
def MAX(inReal: list[float], optInTimePeriod: int = 30) -> list[float]: ...
def MAMA(inReal: list[float], optInFastLimit: float = 0.5, optInSlowLimit: float = 0.05) -> Tuple[list[float], list[float]]: ...
def MACDFIX(inReal: list[float], optInSignalPeriod: int = 9) -> Tuple[list[float], list[float], list[float]]: ...
def MACDEXT(inReal: list[float], optInFastPeriod: int = 12, optInFastMAType: list[int] = 0, optInSlowPeriod: int = 26, optInSlowMAType: list[int] = 0, optInSignalPeriod: int = 9, optInSignalMAType: list[int] = 0) -> Tuple[list[float], list[float], list[float]]: ...
def MACD(inReal: list[float], optInFastPeriod: int = 12, optInSlowPeriod: int = 26, optInSignalPeriod: int = 9) -> Tuple[list[float], list[float], list[float]]: ...
def MA(inReal: list[float], optInTimePeriod: int = 30, optInMAType: list[int] = 0) -> list[float]: ...
def LOG10(inReal: list[float]) -> list[float]: ...
def LN(inReal: list[float]) -> list[float]: ...
def LINEARREG_SLOPE(inReal: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def LINEARREG_INTERCEPT(inReal: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def LINEARREG_ANGLE(inReal: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def LINEARREG(inReal: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def KAMA(inReal: list[float], optInTimePeriod: int = 30) -> list[float]: ...
def HT_TRENDMODE(inReal: list[float]) -> list[int]: ...
def HT_TRENDLINE(inReal: list[float]) -> list[float]: ...
def HT_SINE(inReal: list[float]) -> Tuple[list[float], list[float]]: ...
def HT_PHASOR(inReal: list[float]) -> Tuple[list[float], list[float]]: ...
def HT_DCPHASE(inReal: list[float]) -> list[float]: ...
def HT_DCPERIOD(inReal: list[float]) -> list[float]: ...
def FLOOR(inReal: list[float]) -> list[float]: ...
def EXP(inReal: list[float]) -> list[float]: ...
def EMA(inReal: list[float], optInTimePeriod: int = 30) -> list[float]: ...
def DX(high: list[float], low: list[float], close: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def DEMA(inReal: list[float], optInTimePeriod: int = 30) -> list[float]: ...
def COSH(inReal: list[float]) -> list[float]: ...
def COS(inReal: list[float]) -> list[float]: ...
def CMO(inReal: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def CEIL(inReal: list[float]) -> list[float]: ...
def CDLXSIDEGAP3METHODS(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLUPSIDEGAP2CROWS(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLUNIQUE3RIVER(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLTRISTAR(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLTHRUSTING(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLTASUKIGAP(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLTAKURI(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLSTICKSANDWICH(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLSTALLEDPATTERN(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLSPINNINGTOP(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLSHORTLINE(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLSHOOTINGSTAR(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLSEPARATINGLINES(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLRISEFALL3METHODS(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLRICKSHAWMAN(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLPIERCING(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLONNECK(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLMORNINGSTAR(open: list[float], high: list[float], low: list[float], close: list[float], optInPenetration: float = 0.3) -> list[int]: ...
def CDLMORNINGDOJISTAR(open: list[float], high: list[float], low: list[float], close: list[float], optInPenetration: float = 0.3) -> list[int]: ...
def CDLMATHOLD(open: list[float], high: list[float], low: list[float], close: list[float], optInPenetration: float = 0.5) -> list[int]: ...
def CDLMATCHINGLOW(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLMARUBOZU(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLLONGLINE(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLLONGLEGGEDDOJI(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLLADDERBOTTOM(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLKICKINGBYLENGTH(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLKICKING(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLINVERTEDHAMMER(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLINNECK(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLIDENTICAL3CROWS(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLHOMINGPIGEON(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLHIKKAKEMOD(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLHIKKAKE(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLHIGHWAVE(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLHARAMICROSS(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLHARAMI(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLHANGINGMAN(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLHAMMER(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLGRAVESTONEDOJI(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLGAPSIDESIDEWHITE(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLEVENINGSTAR(open: list[float], high: list[float], low: list[float], close: list[float], optInPenetration: float = 0.3) -> list[int]: ...
def CDLEVENINGDOJISTAR(open: list[float], high: list[float], low: list[float], close: list[float], optInPenetration: float = 0.3) -> list[int]: ...
def CDLENGULFING(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLDRAGONFLYDOJI(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLDOJISTAR(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLDOJI(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLDARKCLOUDCOVER(open: list[float], high: list[float], low: list[float], close: list[float], optInPenetration: float = 0.5) -> list[int]: ...
def CDLCOUNTERATTACK(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLCONCEALBABYSWALL(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLCLOSINGMARUBOZU(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLBREAKAWAY(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLBELTHOLD(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLADVANCEBLOCK(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDLABANDONEDBABY(open: list[float], high: list[float], low: list[float], close: list[float], optInPenetration: float = 0.3) -> list[int]: ...
def CDL3WHITESOLDIERS(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDL3STARSINSOUTH(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDL3OUTSIDE(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDL3LINESTRIKE(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDL3INSIDE(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDL3BLACKCROWS(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CDL2CROWS(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[int]: ...
def CCI(high: list[float], low: list[float], close: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def BOP(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[float]: ...
def BBANDS(inReal: list[float], optInTimePeriod: int = 5, optInNbDevUp: float = 2, optInNbDevDn: float = 2, optInMAType: list[int] = 0) -> Tuple[list[float], list[float], list[float]]: ...
def AVGPRICE(open: list[float], high: list[float], low: list[float], close: list[float]) -> list[float]: ...
def ATR(high: list[float], low: list[float], close: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def ATAN(inReal: list[float]) -> list[float]: ...
def ASIN(inReal: list[float]) -> list[float]: ...
def AROONOSC(high: list[float], low: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def AROON(high: list[float], low: list[float], optInTimePeriod: int = 14) -> Tuple[list[float], list[float]]: ...
def APO(inReal: list[float], optInFastPeriod: int = 12, optInSlowPeriod: int = 26, optInMAType: list[int] = 0) -> list[float]: ...
def ADXR(high: list[float], low: list[float], close: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def ADX(high: list[float], low: list[float], close: list[float], optInTimePeriod: int = 14) -> list[float]: ...
def ADOSC(high: list[float], low: list[float], close: list[float], volume: list[float], optInFastPeriod: int = 3, optInSlowPeriod: int = 10) -> list[float]: ...
def AD(high: list[float], low: list[float], close: list[float], volume: list[float]) -> list[float]: ...
def ACOS(inReal: list[float]) -> list[float]: ...